//! Session log system — the plaintext "black box" beside the exe.
//!
//! Out-of-capsule by design: `Logs/` lives **next to the app** (like the
//! models folder — see [`encaps_logs_dir`]) so it survives exits, wipes and
//! crashes, and can be read without the launch password. It contains
//! **strict metadata only**: timestamps, who did what, which tool, timings,
//! and error diagnostics. Never chat text, never tool outputs, never file
//! contents — the capsule (SQLCipher) stays the only home for private data.
//!
//! Layout:
//! ```text
//! Logs\
//!   Sessions\                 one JSON per app run
//!     23-09-2026_14-02→17-45.json    clean exit: renamed with the end hour
//!     23-09-2026_20-11→….json        open run (crash detection IS the name:
//!                                    a `…` arrow that never got its end)
//!   LogsExplorer.html         the styled viewer (refreshed each launch)
//!   data.js                   catalog the explorer loads via <script> — a
//!                             double-clicked page cannot fetch local JSON
//!                             (file:// restrictions), so the app embeds it
//! ```
//!
//! Events are written live (atomic tmp+rename per event — crash-safe) and the
//! catalog is refreshed on a ~5 s throttle so the current run is watchable.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{Duration, Instant, SystemTime};

use chrono::Local;
use serde::{Deserialize, Serialize};

/// The explorer page (single-file HTML+CSS+JS), written next to Sessions/.
const EXPLORER_HTML: &str = include_str!("assets/LogsExplorer.html");

/// Minimum interval between data.js rewrites while events flow (the run file
/// itself is written on every event — it is only kilobytes).
const CATALOG_MIN_INTERVAL: Duration = Duration::from_secs(5);

/// Folder size above which the UI shows the one-per-launch storage nudge.
pub const NUDGE_BYTES: u64 = 100 * 1024 * 1024;

/// How much of a failed tool's output may appear as the error message —
/// diagnostics, not content.
const ERROR_HEAD: usize = 200;

// ─────────────────────────── data model ────────────────────────────

/// Who generated the event — the nomenclature's "Generated by" column.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum By {
    User,
    Agent,
    Model,
    AmberCore,
}

/// Performance figures attached to an event (the "Perfs" column).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Perfs {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tps: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ttft_ms: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbt_ms: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dur_ms: Option<u64>,
}

/// The error block of a failed event, with the self-debugging layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrBlock {
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub known_bug: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub debug: Option<String>,
}

/// One nomenclature row:
/// `Timestamp | by | type | using | perfs | ✓ / error block`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEvent {
    /// `DD/MM/YY HH:MM:SS`, 24 h, local time.
    pub ts: String,
    pub by: By,
    #[serde(rename = "type")]
    pub typ: String,
    /// Tool used (name + argument signature), when applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub using: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub perfs: Option<Perfs>,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrBlock>,
}

/// Run metadata — the file header written at creation and finalized at exit.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RunHeader {
    /// App version (e.g. "Phoenix Agent 0.8.6").
    pub app: String,
    #[serde(default)]
    pub profile: String,
    #[serde(default)]
    pub workdir: String,
    /// Hardware summary (GPU + RAM + backend).
    #[serde(default)]
    pub hardware: String,
    /// Models used during the run (appended as they load).
    #[serde(default)]
    pub models: Vec<String>,
    /// `DD-MM-YYYY HH:MM` local time.
    pub started: String,
    /// `None` until the clean-exit finalize — a null `ended` is how a crash is
    /// recognized.
    #[serde(default)]
    pub ended: Option<String>,
}

/// A whole session file: `{ "run": …, "events": […] }`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RunFile {
    pub run: RunHeader,
    #[serde(default)]
    pub events: Vec<LogEvent>,
}

// ─────────────────────────── live run state ────────────────────────────

struct Run {
    logs_dir: PathBuf,
    sessions_dir: PathBuf,
    /// File stem (no extension). During the run it ends in `→…`; the clean
    /// exit rename replaces the ellipsis with the end `HH-MM`.
    stem: String,
    header: RunHeader,
    events: Vec<LogEvent>,
    /// Tool-call index → argument signature, captured at ToolStarted so
    /// ToolFinished can log the call without re-parsing the runtime.
    pending_sigs: HashMap<usize, String>,
    /// In-app chat session id tagging subsequent events, when known.
    session: Option<i64>,
    last_catalog: Option<Instant>,
}

impl Run {
    fn path(&self) -> PathBuf {
        self.sessions_dir.join(format!("{}.json", self.stem))
    }
}

static RUN: Mutex<Option<Run>> = Mutex::new(None);

/// The init report, kept for `logs_stats` (first-creation notice, nudge).
static REPORT: Mutex<Option<Report>> = Mutex::new(None);

/// Result of [`init`] — what the UI needs to know about this launch.
#[derive(Debug, Clone, Serialize)]
pub struct Report {
    pub logs_dir: String,
    /// True when `Logs/` itself was created by this launch (first ever run).
    pub first_creation: bool,
    pub swept_clean: usize,
    pub swept_age: usize,
    pub stem: String,
}

/// The last [`init`] report (None before init / in tests).
pub fn report() -> Option<Report> {
    REPORT.lock().unwrap().clone()
}

/// The explorer page bytes (served by the local explorer server).
pub fn explorer_html() -> &'static str {
    EXPLORER_HTML
}

// ─────────────────────────── time helpers ────────────────────────────

fn now_ts() -> String {
    Local::now().format("%d/%m/%y %H:%M:%S").to_string()
}

fn now_day_hm() -> String {
    Local::now().format("%d-%m-%Y %H:%M").to_string()
}

fn now_hm() -> String {
    Local::now().format("%H-%M").to_string()
}

// ─────────────────────────── location ────────────────────────────

/// The user-facing logs root: `Logs/` **beside the exe** (portable — travels
/// with the launcher, survives staging wipes), falling back to
/// `<data dir>/Logs` when the exe folder is unwritable or in debug builds
/// (mirrors [`crate::config::encaps_models_dir`]).
pub fn encaps_logs_dir(data_dir: &Path) -> PathBuf {
    #[cfg(not(debug_assertions))]
    {
        if std::env::var_os("PHOENIX_ENCAPS_PORTABLE").is_none() {
            if let Some(dir) = std::env::current_exe()
                .ok()
                .and_then(|p| p.parent().map(|d| d.join("Logs")))
            {
                if crate::config::dir_writable(&dir) {
                    return dir;
                }
            }
        }
    }
    data_dir.join("Logs")
}

// ─────────────────────────── init / finalize ────────────────────────────

/// Create the Logs layout, apply retention, and open this run's file.
/// `header` carries app/profile/workdir/hardware/models (started/ended are
/// set here). Idempotent per process; call once at launch.
pub fn init(data_dir: &Path, mut header: RunHeader, auto_clean: bool, keep_days: u32) -> Report {
    let logs_dir = encaps_logs_dir(data_dir);
    let first_creation = !logs_dir.exists();
    let sessions_dir = logs_dir.join("Sessions");
    let _ = std::fs::create_dir_all(&sessions_dir);
    // Refresh the explorer every launch so viewer updates ship with app
    // updates (it is a generated artifact, not user data).
    atomic_write(&logs_dir.join("LogsExplorer.html"), EXPLORER_HTML.as_bytes());

    let (swept_clean, swept_age) = sweep(&sessions_dir, auto_clean, keep_days);

    header.started = now_day_hm();
    let base = Local::now().format("%d-%m-%Y_%H-%M").to_string();
    let mut stem = format!("{base}→…");
    let mut n = 2;
    while sessions_dir.join(format!("{stem}.json")).exists() {
        stem = format!("{base}→…-{n}");
        n += 1;
    }

    let mut run = Run {
        logs_dir: logs_dir.clone(),
        sessions_dir,
        stem: stem.clone(),
        header,
        events: vec![LogEvent {
            ts: now_ts(),
            by: By::Agent,
            typ: "AppStart".into(),
            using: None,
            perfs: None,
            ok: true,
            error: None,
        }],
        pending_sigs: HashMap::new(),
        session: None,
        last_catalog: None,
    };
    persist(&run);
    write_catalog(&run.logs_dir);
    run.last_catalog = Some(Instant::now());
    let report = Report {
        logs_dir: logs_dir.display().to_string(),
        first_creation,
        swept_clean,
        swept_age,
        stem,
    };
    *REPORT.lock().unwrap() = Some(report.clone());
    *RUN.lock().unwrap() = Some(run);
    report
}

/// Clean exit: stamp `ended`, rename `…` to the end hour, refresh the
/// catalog. A crash never runs this — the open `…` arrow in the file name is
/// the crash marker.
pub fn finalize() {
    let mut guard = RUN.lock().unwrap();
    let Some(mut run) = guard.take() else { return };
    run.header.ended = Some(now_day_hm());
    let old_path = run.path();
    // Write the finalized content under the OLD name first, then rename: a
    // crash at any point leaves a coherent file (either the open name with
    // `ended` already set, or the final name).
    persist(&run);
    let new_stem = run.stem.replace('…', &now_hm());
    let new_path = run.sessions_dir.join(format!("{new_stem}.json"));
    if !new_path.exists() {
        let _ = std::fs::rename(&old_path, &new_path);
    }
    run.stem = new_stem;
    write_catalog(&run.logs_dir);
}

// ─────────────────────────── event API ────────────────────────────

/// Append an event to the run (persisted immediately; catalog throttled).
pub fn log(
    by: By,
    typ: &str,
    using: Option<String>,
    perfs: Option<Perfs>,
    ok: bool,
    error: Option<ErrBlock>,
) {
    let mut guard = RUN.lock().unwrap();
    let Some(run) = guard.as_mut() else { return };
    run.events.push(LogEvent {
        ts: now_ts(),
        by,
        typ: typ.to_string(),
        using,
        perfs,
        ok,
        error,
    });
    persist(run);
    maybe_catalog(run);
}

/// A successful event with no extras: `(ts | by | type | — | — | ✓)`.
pub fn simple(by: By, typ: &str) {
    log(by, typ, None, None, true, None);
}

/// Record an error event, running the known-bug catalog over the message.
pub fn error_now(typ: &str, using: Option<String>, message: &str) {
    let (by, known) = classify_error(message);
    let error = ErrBlock {
        message: head(message, ERROR_HEAD * 2),
        known_bug: known.map(|(id, _)| id.to_string()),
        debug: known.map(|(_, debug)| debug.to_string()),
    };
    log(by, typ, using, None, false, Some(error));
}

/// Tag subsequent events with the in-app chat session id (`/new` switches it).
pub fn set_session(id: Option<i64>) {
    if let Some(run) = RUN.lock().unwrap().as_mut() {
        run.session = id;
    }
}

/// Append a model to the run header (deduped) and persist.
pub fn note_model(tag: &str) {
    if let Some(run) = RUN.lock().unwrap().as_mut() {
        if !run.header.models.iter().any(|m| m == tag) {
            run.header.models.push(tag.to_string());
            persist(run);
        }
    }
}

/// Update the run header's profile name (sidebar profile switch).
pub fn set_profile(profile: &str) {
    if let Some(run) = RUN.lock().unwrap().as_mut() {
        run.header.profile = profile.to_string();
        persist(run);
    }
}

/// Tool call started — remember the argument signature for the finish event.
pub fn tool_started(index: usize, name: &str, args: &str) {
    let sig = format!("{name}({})", signature(args));
    if let Some(run) = RUN.lock().unwrap().as_mut() {
        run.pending_sigs.insert(index, sig);
    }
}

/// Tool call finished — the main audit row (name + signature + duration +
/// outcome). Failed calls carry the head of the output as the error message;
/// successful calls never log their output.
pub fn tool_finished(index: usize, name: &str, success: bool, result: &str, duration_ms: Option<u64>) {
    let using = {
        let mut guard = RUN.lock().unwrap();
        match guard.as_mut() {
            Some(run) => run.pending_sigs.remove(&index).unwrap_or_else(|| name.to_string()),
            None => name.to_string(),
        }
    };
    let error = if success {
        None
    } else {
        let (.., known) = classify_error(result);
        Some(ErrBlock {
            message: head(result, ERROR_HEAD),
            known_bug: known.map(|(id, _)| id.to_string()),
            debug: known.map(|(_, debug)| debug.to_string()),
        })
    };
    log(
        By::Agent,
        tool_type(name),
        Some(using),
        Some(Perfs { dur_ms: duration_ms, ..Default::default() }),
        success,
        error,
    );
}

/// A write tool was denied by the user.
pub fn tool_denied(index: usize, name: &str) {
    let using = {
        let mut guard = RUN.lock().unwrap();
        match guard.as_mut() {
            Some(run) => run.pending_sigs.remove(&index).unwrap_or_else(|| name.to_string()),
            None => name.to_string(),
        }
    };
    log(
        By::User,
        "Validation",
        Some(using),
        None,
        false,
        Some(ErrBlock { message: "Denied by user".into(), known_bug: None, debug: None }),
    );
}

/// Mirror an AmberCore engine event into the session log. These are the
/// SILENT happenings that never fail a request — above all the OOM CPU
/// fallback — so nothing else in the app would ever see them. Drained from
/// the engine's broadcast channel by the task spawned in `web::run`.
pub fn engine_event(ev: &ambercore::server::EngineEvent) {
    use ambercore::server::EngineEvent;
    match ev {
        EngineEvent::OomFallback { tag } => {
            // An error that got recovered — logged AS an error (with its
            // known-bug entry) so the run is preserved by clean-run deletion.
            let (_, known) = classify_error("cuda_error_out_of_memory");
            log(
                By::AmberCore,
                "OomFallback",
                Some(tag.clone()),
                None,
                false,
                Some(ErrBlock {
                    message: "GPU build ran out of VRAM — the model was rebuilt on the CPU \
                              (slower, the turn kept running)"
                        .into(),
                    known_bug: known.map(|(id, _)| id.to_string()),
                    debug: known.map(|(_, d)| d.to_string()),
                }),
            );
        }
        EngineEvent::ModelLoaded { tag, device, dur_ms } => {
            note_model(tag);
            log(
                By::AmberCore,
                "ModelLoad",
                Some(format!("{tag} · {device}")),
                Some(Perfs { dur_ms: Some(*dur_ms), ..Default::default() }),
                true,
                None,
            );
        }
        EngineEvent::ModelUnloaded { tag } => {
            log(By::AmberCore, "ModelUnload", Some(tag.clone()), None, true, None);
        }
        EngineEvent::VramWarning { message } => {
            log(By::AmberCore, "VramWarning", Some(head(message, ERROR_HEAD)), None, true, None);
        }
    }
}

// ─────────────────────────── classification ────────────────────────────

/// The nomenclature's "Type" for a tool name (Message/Writing/Reading/
/// Exploring/Diffusing… plus the additions the app needs).
pub fn tool_type(name: &str) -> &'static str {
    let n = name.to_ascii_lowercase();
    if n.contains("delegate") {
        "SubAgent"
    } else if n.contains("todo") || n.contains("plan") {
        "Planning"
    } else if n.contains("web") || n.contains("fetch") || n.contains("browse") || n.contains("diffus") {
        "Diffusing"
    } else if n.contains("write") || n.contains("edit") || n.contains("save") || n.contains("create") {
        "Writing"
    } else if n.contains("list") || n.contains("dir") || n.contains("tree") || n.contains("explore") {
        "Exploring"
    } else if n.contains("read") || n.contains("grep") || n.contains("search") || n.contains("glob") {
        "Reading"
    } else if n.contains("shell") || n.contains("run") || n.contains("exec") || n.contains("command") {
        "Executing"
    } else {
        "Tool"
    }
}

/// Compact argument signature: the top-level JSON keys + a size hint. Never
/// the argument VALUES (they may be file contents).
pub fn signature(args: &str) -> String {
    let keys: Vec<String> = serde_json::from_str::<serde_json::Value>(args)
        .ok()
        .and_then(|v| v.as_object().map(|o| o.keys().cloned().collect()))
        .unwrap_or_default();
    let mut sig = if keys.is_empty() {
        format!("{} chars", args.chars().count())
    } else {
        format!("{} · {} chars", keys.join(", "), args.chars().count())
    };
    if sig.chars().count() > 80 {
        sig = format!("{}…", sig.chars().take(79).collect::<String>());
    }
    sig
}

/// The known-bug catalog: error signature → (id, debug instruction). This is
/// the self-debugging layer — grow it as bugs are met in the field.
fn known_bug(msg: &str) -> Option<(&'static str, &'static str)> {
    let m = msg.to_ascii_lowercase();
    if m.contains("cuda_error_out_of_memory")
        || (m.contains("out of memory") && (m.contains("cuda") || m.contains("candle")))
    {
        return Some((
            "OOM-CUDA-01",
            "Free VRAM below the model size. Close GPU-hungry apps or unload the other \
             model; the CPU fallback keeps the turn alive (slower but safe).",
        ));
    }
    if m.contains("cuda_error") || (m.contains("driver") && m.contains("cuda")) {
        return Some((
            "DRIVER-CUDA-01",
            "CUDA driver/toolkit mismatch for this build. Try the other launcher \
             (CUDA12 vs CUDA13), or update the NVIDIA driver.",
        ));
    }
    if m.contains("database is locked") || m.contains("sqlcipher") {
        return Some((
            "DB-LOCKED-01",
            "The encrypted database was busy (concurrent access or an unclean exit). \
             Restart the app — the WAL checkpoint on seal repairs it.",
        ));
    }
    if m.contains("manifest") && (m.contains("corrupt") || m.contains("parse") || m.contains("missing")) {
        return Some((
            "MANIFEST-01",
            "The AmberCore catalog manifest is damaged. Deleting models/manifest.json \
             makes the next launch rescan the models folder and rebuild it.",
        ));
    }
    if m.contains("gguf") && (m.contains("magic") || m.contains("header") || m.contains("invalid")) {
        return Some((
            "GGUF-01",
            "The GGUF file is truncated or not a GGUF. Re-download the model \
             (delete it in the Models panel first).",
        ));
    }
    if m.contains("connection refused")
        || m.contains("dns")
        || m.contains("timed out")
        || m.contains("error sending request")
        || m.contains("request failed")
    {
        return Some((
            "NET-CONN-01",
            "A URL was unreachable (offline, DNS, or the host is down). Check the \
             network; if Ollama: start it (`ollama serve`). If a remote AmberCore: \
             check the machine and port.",
        ));
    }
    if m.contains("wrong launch password") || m.contains("unwrap") {
        return Some((
            "UNLOCK-01",
            "The launch password did not unwrap the key bundle. Retype it; if lost, \
             recover via 2FA or the fixed DB password as a last resort.",
        ));
    }
    None
}

/// Best-effort attribution ("Generated by") + known-bug lookup for an error
/// message. Engine signatures (candle/CUDA/GGUF/VRAM) attribute to AmberCore,
/// database trouble to the app, everything else to the model pipeline.
fn classify_error(msg: &str) -> (By, Option<(&'static str, &'static str)>) {
    let m = msg.to_ascii_lowercase();
    let by = if m.contains("candle")
        || m.contains("cuda")
        || m.contains("gguf")
        || m.contains("vram")
        || m.contains("ambercore")
    {
        By::AmberCore
    } else if m.contains("sqlcipher") || m.contains("database") || m.contains("sql") {
        By::Agent
    } else {
        By::Model
    };
    (by, known_bug(msg))
}

fn head(s: &str, n: usize) -> String {
    let mut out: String = s.chars().take(n).collect();
    if s.chars().count() > n {
        out.push('…');
    }
    out.replace('\n', " ⏎ ")
}

// ─────────────────────────── persistence ────────────────────────────

/// Write the run file atomically (tmp + rename) so a crash mid-write can
/// never truncate the previous good state.
fn persist(run: &Run) {
    let file = RunFile { run: run.header.clone(), events: run.events.clone() };
    match serde_json::to_vec_pretty(&file) {
        Ok(bytes) => atomic_write(&run.path(), &bytes),
        Err(e) => tracing::warn!("logsys: serialize run file: {e}"),
    }
}

fn maybe_catalog(run: &mut Run) {
    let due = run
        .last_catalog
        .map(|t| t.elapsed() >= CATALOG_MIN_INTERVAL)
        .unwrap_or(true);
    if due {
        write_catalog(&run.logs_dir);
        run.last_catalog = Some(Instant::now());
    }
}

fn atomic_write(path: &Path, bytes: &[u8]) {
    let tmp = path.with_file_name(format!(
        "{}.tmp",
        path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default()
    ));
    if let Err(e) = std::fs::write(&tmp, bytes).and_then(|_| std::fs::rename(&tmp, path)) {
        tracing::warn!("logsys: write {}: {e}", path.display());
    }
}

// ─────────────────────────── catalog (data.js) ────────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct CatalogEntry {
    pub file: String,
    /// File mtime (unix seconds) — lets the explorer tell a LIVE run (fresh
    /// mtime, `ended` null) from a crashed one (stale mtime, `ended` null).
    pub mtime: u64,
    /// `None` when the file failed to parse (shown as a broken entry).
    pub run: Option<RunFile>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Catalog {
    pub generated_at: String,
    pub sessions_dir: String,
    pub app_version: String,
    /// Newest first (by mtime).
    pub runs: Vec<CatalogEntry>,
}

/// Scan the Sessions folder and build the catalog.
pub fn build_catalog(logs_dir: &Path) -> Catalog {
    let sessions_dir = logs_dir.join("Sessions");
    let mut entries: Vec<CatalogEntry> = std::fs::read_dir(&sessions_dir)
        .map(|rd| {
            rd.flatten()
                .filter(|e| e.path().extension().map(|x| x == "json").unwrap_or(false))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default()
        .into_iter()
        .map(|e| {
            let path = e.path();
            let file = path
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default();
            let mtime = e
                .metadata()
                .and_then(|m| m.modified())
                .ok()
                .and_then(|t| t.duration_since(SystemTime::UNIX_EPOCH).ok())
                .map(|d| d.as_secs())
                .unwrap_or(0);
            let run = std::fs::read_to_string(&path)
                .ok()
                .and_then(|text| serde_json::from_str::<RunFile>(&text).ok());
            CatalogEntry { file, mtime, run }
        })
        .collect();
    // Live/current runs (fresh mtime) sink to the top by sorting on mtime desc.
    entries.sort_by(|a, b| b.mtime.cmp(&a.mtime));
    Catalog {
        generated_at: now_ts(),
        sessions_dir: sessions_dir.display().to_string(),
        app_version: env!("CARGO_PKG_VERSION").to_string(),
        runs: entries,
    }
}

/// Write `data.js` (the catalog the explorer loads via `<script>`).
pub fn write_catalog(logs_dir: &Path) {
    let catalog = build_catalog(logs_dir);
    match serde_json::to_string(&catalog) {
        Ok(json) => atomic_write(
            &logs_dir.join("data.js"),
            format!("window.PA_LOGS = {json};\n").as_bytes(),
        ),
        Err(e) => tracing::warn!("logsys: serialize catalog: {e}"),
    }
}

// ─────────────────────────── maintenance ────────────────────────────

/// Folder stats for the Settings tab and the nudge.
#[derive(Debug, Clone, Serialize)]
pub struct Stats {
    pub sessions: usize,
    pub size_bytes: u64,
    pub logs_dir: String,
}

pub fn stats(logs_dir: &Path) -> Stats {
    let sessions_dir = logs_dir.join("Sessions");
    let mut size: u64 = 0;
    let mut sessions = 0usize;
    if let Ok(rd) = std::fs::read_dir(logs_dir) {
        for e in rd.flatten() {
            if e.metadata().map(|m| m.is_file()).unwrap_or(false) {
                size += e.metadata().map(|m| m.len()).unwrap_or(0);
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(&sessions_dir) {
        for e in rd.flatten() {
            if e.path().extension().map(|x| x == "json").unwrap_or(false) {
                sessions += 1;
                size += e.metadata().map(|m| m.len()).unwrap_or(0);
            }
        }
    }
    Stats { sessions, size_bytes: size, logs_dir: logs_dir.display().to_string() }
}

/// Parse the `DD-MM-YYYY` prefix of a run file stem into a date.
fn stem_date(file: &str) -> Option<chrono::NaiveDate> {
    let day = file.get(0..2)?;
    let month = file.get(3..5)?;
    let year = file.get(6..10)?;
    chrono::NaiveDate::from_ymd_opt(
        year.parse().ok()?,
        month.parse().ok()?,
        day.parse().ok()?,
    )
}

fn is_clean(file: &Path) -> bool {
    std::fs::read_to_string(file)
        .ok()
        .and_then(|t| serde_json::from_str::<RunFile>(&t).ok())
        .map(|rf| rf.run.ended.is_some() && rf.events.iter().all(|e| e.ok))
        .unwrap_or(false)
}

/// Apply the retention policy. Returns `(clean_deleted, age_deleted)`. Never
/// touches runs with errors, crashed runs (open arrow / no `ended`), or
/// unparseable files.
pub fn sweep(sessions_dir: &Path, auto_clean: bool, keep_days: u32) -> (usize, usize) {
    let mut clean_deleted = 0;
    let mut age_deleted = 0;
    let cutoff = (keep_days > 0).then(|| Local::now() - chrono::Duration::days(keep_days as i64));
    let Ok(rd) = std::fs::read_dir(sessions_dir) else { return (0, 0) };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.extension().map(|x| x == "json").unwrap_or(false) == false {
            continue;
        }
        let name = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
        // Age policy applies to ended runs only — never the live one.
        if let Some(cutoff) = cutoff {
            if let Some(date) = stem_date(&name) {
                let ended = std::fs::read_to_string(&path)
                    .ok()
                    .and_then(|t| serde_json::from_str::<RunFile>(&t).ok())
                    .map(|rf| rf.run.ended.is_some())
                    .unwrap_or(false);
                if ended && date < cutoff.date_naive() {
                    if std::fs::remove_file(&path).is_ok() {
                        age_deleted += 1;
                        continue;
                    }
                }
            }
        }
        if auto_clean && is_clean(&path) {
            if std::fs::remove_file(&path).is_ok() {
                clean_deleted += 1;
            }
        }
    }
    (clean_deleted, age_deleted)
}

/// Deletion scopes for the Settings tab / the served explorer's cleanup API.
#[derive(Debug, Clone)]
pub enum DeleteScope {
    /// All runs that [`sweep`] would call clean (no errors + ended).
    Clean,
    /// Every run file.
    All,
    /// Specific file names.
    Files(Vec<String>),
}

/// Delete per scope, refresh the catalog, return how many files were removed.
pub fn delete(logs_dir: &Path, scope: DeleteScope) -> usize {
    let sessions_dir = logs_dir.join("Sessions");
    let mut removed = 0;
    match scope {
        DeleteScope::Clean => {
            removed = sweep(&sessions_dir, true, 0).0;
        }
        DeleteScope::All => {
            if let Ok(rd) = std::fs::read_dir(&sessions_dir) {
                for e in rd.flatten() {
                    let p = e.path();
                    if p.extension().map(|x| x == "json").unwrap_or(false)
                        && std::fs::remove_file(&p).is_ok()
                    {
                        removed += 1;
                    }
                }
            }
        }
        DeleteScope::Files(files) => {
            for name in files {
                // Only ever delete inside Sessions/, and only .json files.
                if !name.ends_with(".json") || name.contains('/') || name.contains('\\') {
                    continue;
                }
                if std::fs::remove_file(sessions_dir.join(&name)).is_ok() {
                    removed += 1;
                }
            }
        }
    }
    write_catalog(logs_dir);
    removed
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("pa-logsys-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn header() -> RunHeader {
        RunHeader {
            app: "Phoenix Agent test".into(),
            profile: "home".into(),
            workdir: "N:\\somewhere".into(),
            hardware: "TestGPU 6 GB".into(),
            models: vec!["test-model".into()],
            started: String::new(),
            ended: None,
        }
    }

    #[test]
    fn known_bug_catalog_matches_field_signatures() {
        assert_eq!(known_bug("candle error: DriverError(CUDA_ERROR_OUT_OF_MEMORY, \"out of memory\")").unwrap().0, "OOM-CUDA-01");
        assert_eq!(known_bug("Wrong launch password.").unwrap().0, "UNLOCK-01");
        assert_eq!(known_bug("connection refused (os error 10061)").map(|(id, _)| id), Some("NET-CONN-01"));
        assert_eq!(
            known_bug("request failed: error sending request for url (https://huggingface.co/…)")
                .map(|(id, _)| id),
            Some("NET-CONN-01"),
            "the RWKV7 pull failure phrasing maps to the network bug"
        );
        assert!(known_bug("model produced garbage").is_none());
        let (by, _) = classify_error("candle cuda boom");
        assert_eq!(by, By::AmberCore);
        let (by, _) = classify_error("the model rambled");
        assert_eq!(by, By::Model);
    }

    #[test]
    fn signature_lists_keys_without_values() {
        let sig = signature(r#"{"path": "N:\\secret\\file.txt", "content": "TOP SECRET"}"#);
        assert!(sig.contains("path") && sig.contains("content"));
        assert!(!sig.contains("TOP SECRET"), "values never leak into the log");
    }

    #[test]
    fn tool_type_maps_user_vocabulary() {
        assert_eq!(tool_type("list_dir"), "Exploring");
        assert_eq!(tool_type("read_file"), "Reading");
        assert_eq!(tool_type("write_file"), "Writing");
        assert_eq!(tool_type("run_command"), "Executing");
        assert_eq!(tool_type("delegate"), "SubAgent");
    }

    #[test]
    fn sweep_deletes_only_clean_ended_runs() {
        let dir = tmpdir("sweep");
        let sessions = dir.join("Sessions");
        std::fs::create_dir_all(&sessions).unwrap();

        // Clean + ended → deletable.
        let clean = RunFile {
            run: RunHeader { ended: Some("x".into()), ..Default::default() },
            events: vec![],
        };
        // Ended but contains an error → kept.
        let errored = RunFile {
            run: RunHeader { ended: Some("x".into()), ..Default::default() },
            events: vec![LogEvent {
                ts: "t".into(),
                by: By::Model,
                typ: "Error".into(),
                using: None,
                perfs: None,
                ok: false,
                error: None,
            }],
        };
        // Crashed (no ended, whatever the name) → kept even when all events ok.
        let crashed = RunFile { run: RunHeader::default(), events: vec![] };

        std::fs::write(sessions.join("01-01-2026_10-00→11-00.json"), serde_json::to_string(&clean).unwrap()).unwrap();
        std::fs::write(sessions.join("01-01-2026_12-00→13-00.json"), serde_json::to_string(&errored).unwrap()).unwrap();
        std::fs::write(sessions.join("01-01-2026_14-00→….json"), serde_json::to_string(&crashed).unwrap()).unwrap();

        let (deleted, _) = sweep(&sessions, true, 0);
        assert_eq!(deleted, 1);
        assert!(!sessions.join("01-01-2026_10-00→11-00.json").exists());
        assert!(sessions.join("01-01-2026_12-00→13-00.json").exists());
        assert!(sessions.join("01-01-2026_14-00→….json").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn sweep_age_policy_uses_stem_date_and_skips_open_runs() {
        let dir = tmpdir("age");
        let sessions = dir.join("Sessions");
        std::fs::create_dir_all(&sessions).unwrap();
        let ended = RunFile { run: RunHeader { ended: Some("x".into()), ..Default::default() }, events: vec![] };
        // The crashed twin has the same old stem date but NO `ended` — content
        // is the truth, the open arrow alone doesn't protect a finalized file.
        let crashed = RunFile { run: RunHeader::default(), events: vec![] };
        std::fs::write(sessions.join("01-01-2020_10-00→11-00.json"), serde_json::to_string(&ended).unwrap()).unwrap();
        std::fs::write(sessions.join("01-01-2020_12-00→….json"), serde_json::to_string(&crashed).unwrap()).unwrap();

        let (_, aged) = sweep(&sessions, false, 30);
        assert_eq!(aged, 1, "old ended run deleted, crashed twin kept");
        assert!(sessions.join("01-01-2020_12-00→….json").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    // The init → events → finalize lifecycle owns the global RUN state, so the
    // lifecycle assertions live in ONE serial test (parallel tests would race
    // the static).
    #[test]
    fn lifecycle_init_log_finalize_catalog_and_collision() {
        let dir = tmpdir("lifecycle");

        // ── init: layout + open arrow ──
        let report = init(&dir, header(), false, 0);
        assert!(report.first_creation, "first run creates Logs/");
        assert!(dir.join("Logs/Sessions").is_dir());
        assert!(dir.join("Logs/LogsExplorer.html").is_file());
        assert!(dir.join("Logs/data.js").is_file());
        assert!(report.stem.contains("→…"), "open stem during the run: {}", report.stem);
        let rf: RunFile = serde_json::from_str(
            &std::fs::read_to_string(
                dir.join("Logs/Sessions").join(format!("{}.json", report.stem)),
            )
            .unwrap(),
        )
        .unwrap();
        assert_eq!(rf.run.app, "Phoenix Agent test");
        assert_eq!(rf.events[0].typ, "AppStart");
        assert!(rf.run.ended.is_none());

        // ── events: message, OOM error, model header growth ──
        simple(By::User, "Message");
        note_model("rwkv7-2.9b");
        error_now("ModelLoad", Some("rwkv7".into()), "candle error: CUDA_ERROR_OUT_OF_MEMORY");

        // ── engine events: the SILENT recoveries (OOM CPU fallback & co.) ──
        engine_event(&ambercore::server::EngineEvent::OomFallback { tag: "rwkv7-2.9b".into() });
        engine_event(&ambercore::server::EngineEvent::ModelLoaded {
            tag: "rwkv7-2.9b".into(),
            device: "cpu".into(),
            dur_ms: 2100,
        });
        engine_event(&ambercore::server::EngineEvent::ModelUnloaded { tag: "qwen3.5".into() });
        engine_event(&ambercore::server::EngineEvent::VramWarning {
            message: "Low VRAM headroom (0.3 GB) — WDDM may spill to system RAM".into(),
        });

        // ── crash simulation: a second run starts while the first is open ──
        *RUN.lock().unwrap() = None;
        let second = init(&dir, header(), false, 0);
        assert_ne!(report.stem, second.stem, "same-minute runs never overwrite");

        // ── finalize: rename `…` → end hour, ended set, catalog lists it ──
        finalize();
        let sessions: Vec<String> = std::fs::read_dir(dir.join("Logs/Sessions"))
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        assert_eq!(sessions.len(), 2, "crashed twin + finalized run coexist");
        let finalized = sessions.iter().find(|s| !s.contains('…')).expect("renamed at exit");
        assert!(finalized.contains('→'));

        let rf: RunFile = serde_json::from_str(
            &std::fs::read_to_string(dir.join("Logs/Sessions").join(finalized)).unwrap(),
        )
        .unwrap();
        assert!(rf.run.ended.is_some(), "the clean exit is stamped");

        // The crashed twin kept everything the first run had logged.
        let crashed_rf: RunFile = serde_json::from_str(
            &std::fs::read_to_string(dir.join("Logs/Sessions").join(format!("{}.json", report.stem)))
                .unwrap(),
        )
        .unwrap();
        assert!(crashed_rf.run.ended.is_none(), "no ended on a crashed run");
        assert!(crashed_rf.run.models.contains(&"rwkv7-2.9b".to_string()), "header collected the model");
        let oom = crashed_rf.events.iter().find(|e| !e.ok).expect("the OOM event is kept");
        assert_eq!(oom.error.as_ref().unwrap().known_bug.as_deref(), Some("OOM-CUDA-01"));

        // The silent engine recoveries landed with their diagnostics.
        let fb = crashed_rf.events.iter().find(|e| e.typ == "OomFallback").expect("fallback logged");
        assert!(!fb.ok, "the fallback is an error-that-recovered");
        assert_eq!(fb.error.as_ref().unwrap().known_bug.as_deref(), Some("OOM-CUDA-01"));
        let ml = crashed_rf
            .events
            .iter()
            .find(|e| e.typ == "ModelLoad" && e.using.as_deref().is_some_and(|u| u.ends_with("cpu")))
            .expect("engine load logged");
        assert_eq!(ml.using.as_deref(), Some("rwkv7-2.9b · cpu"));
        assert_eq!(ml.perfs.as_ref().unwrap().dur_ms, Some(2100));
        assert!(crashed_rf.events.iter().any(|e| e.typ == "ModelUnload"));
        assert!(crashed_rf.events.iter().any(|e| e.typ == "VramWarning"));

        let catalog: serde_json::Value = serde_json::from_str(
            std::fs::read_to_string(dir.join("Logs/data.js"))
                .unwrap()
                .trim_start_matches("window.PA_LOGS = ")
                .trim_end_matches(|c: char| c == ';' || c.is_whitespace()),
        )
        .unwrap();
        assert_eq!(catalog["runs"].as_array().unwrap().len(), 2);

        // Leave the global clean for any later test.
        *RUN.lock().unwrap() = None;
        let _ = std::fs::remove_dir_all(&dir);
    }
}
